
FROM openjdk:11

ADD ./target/spring-angular-socket-0.0.1-SNAPSHOT.jar /usr/src/spring-angular-socket-0.0.1-SNAPSHOT.jar

WORKDIR usr/src

ENTRYPOINT ["java","-jar", "spring-angular-socket-0.0.1-SNAPSHOT.jar"]